### ISSUE TITLE
Document recommended resources for learning Clojure

### ISSUE THREAD

**Issue by aviflax** [aviflax/omnia#2]
If we want to enable community contributions to Omnia, we’ll need to give people some pointers to learning Clojure, e.g. [Clojure for the Brave and True](http://www.braveclojure.com).

cc @aprilrabkin

**Comment by aviflax** [comment]
[4clojure](http://www.4clojure.com):

> 4Clojure is a resource to help fledgling clojurians learn the language through interactive problems. The first few problems are easy enough that even someone with no prior experience should find the learning curve forgiving.

**Comment by aviflax** [comment]
Maybe http://www.clojurenewbieguide.com

**Comment by aprilrabkin** [comment]
Thanks, Avi! I look forward to having time to learn Clojure.

**Comment by aviflax** [comment]
@aprilrabkin my pleasure! let me know how I can help!
